# Generated by Django 5.2 on 2025-05-04 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "auctions_ethauction" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "contract_address" varchar(42) NOT NULL,
                "contract_auction_id" integer unsigned NOT NULL CHECK ("contract_auction_id" >= 0),
                "seller_address" varchar(42) NOT NULL,
                "start_block" integer unsigned NOT NULL CHECK ("start_block" >= 0),
                "end_block" integer unsigned NULL CHECK ("end_block" >= 0),
                "last_sync_block" integer unsigned NOT NULL CHECK ("last_sync_block" >= 0),
                "auction_id" integer NOT NULL REFERENCES "auctions_auction" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            """,
            """
            DROP TABLE IF EXISTS "auctions_ethauction";
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS "auctions_et_contrac_e95f3b_idx" ON "auctions_ethauction" ("contract_address", "contract_auction_id");
            """,
            """
            DROP INDEX IF EXISTS "auctions_et_contrac_e95f3b_idx";
            """
        ),
        migrations.RunSQL(
            """
            CREATE UNIQUE INDEX IF NOT EXISTS "auctions_ethauction_auction_id_db7cd7bc_uniq" ON "auctions_ethauction" ("auction_id");
            """,
            """
            DROP INDEX IF EXISTS "auctions_ethauction_auction_id_db7cd7bc_uniq";
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS "auctions_ethauction_auction_id_db7cd7bc" ON "auctions_ethauction" ("auction_id");
            """,
            """
            DROP INDEX IF EXISTS "auctions_ethauction_auction_id_db7cd7bc";
            """
        ),
    ]
