# Generated by Django 5.2 on 2025-05-04 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20250504_1430'),
    ]

    operations = [
        migrations.RunSQL(
            """
            CREATE TABLE IF NOT EXISTS "auctions_ethbid" (
                "id" integer NOT NULL PRIMARY KEY AUTOINCREMENT,
                "bidder_address" varchar(42) NOT NULL,
                "amount_wei" varchar(78) NOT NULL,
                "transaction_hash" varchar(66) NOT NULL UNIQUE,
                "block_number" integer unsigned NOT NULL CHECK ("block_number" >= 0),
                "timestamp" datetime NOT NULL,
                "eth_auction_id" integer NOT NULL REFERENCES "auctions_ethauction" ("id") DEFERRABLE INITIALLY DEFERRED
            );
            """,
            """
            DROP TABLE IF EXISTS "auctions_ethbid";
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS "auctions_et_bidder__04adee_idx" ON "auctions_ethbid" ("bidder_address");
            """,
            """
            DROP INDEX IF EXISTS "auctions_et_bidder__04adee_idx";
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS "auctions_et_transac_19b825_idx" ON "auctions_ethbid" ("transaction_hash");
            """,
            """
            DROP INDEX IF EXISTS "auctions_et_transac_19b825_idx";
            """
        ),
        migrations.RunSQL(
            """
            CREATE INDEX IF NOT EXISTS "auctions_ethbid_eth_auction_id_1a8d4988" ON "auctions_ethbid" ("eth_auction_id");
            """,
            """
            DROP INDEX IF EXISTS "auctions_ethbid_eth_auction_id_1a8d4988";
            """
        ),
    ]
