# Generated by Django 5.2 on 2025-05-04 15:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_auto_20250504_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='RazorpayPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=100, unique=True)),
                ('payment_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=3)),
                ('receipt', models.CharField(blank=True, max_length=100, null=True)),
                ('status', models.CharField(default='created', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='ethbid',
            name='auctions_et_transac_19b825_idx',
        ),
        migrations.AddIndex(
            model_name='ethbid',
            index=models.Index(fields=['block_number'], name='auctions_et_block_n_7e01b7_idx'),
        ),
        migrations.AddField(
            model_name='razorpaypayment',
            name='auction',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='razorpay_payment', to='auctions.auction'),
        ),
    ]
